services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n #尝试y
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: # mountj a directory as a volumne
      #- ./dags:/dag # dag folder
      #- C:\Users\ryanb\d2l-en\ETL\ETL\dags\:/usr/local/airflow/dag
      - "C:/Users/ryanb/d2l-en/ETL/ETL/dags:/usr/local/airflow/dag"
      - "C:/Users/ryanb/d2l-en/ETL/ETL/dags:/dag"
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3