[supervisord]
nodaemon=true

[program:airflow-webserver]
command=airflow webserver
stdout_logfile=/airflow/app/logs/webserver.out.log
stderr_logfile=/airflow/app/logs/webserver.err.log
autostart=true
autorestart=true

[program:airflow-scheduler]
command=airflow scheduler
autostart=true
autorestart=true
stderr_logfile=/airflow/app/logs/scheduler.err.log
stdout_logfile=/airflow/app/logs/scheduler.out.log

; Optional Celery worker
; Uncomment if you are using CeleryExecutor
; [program:airflow-worker]
; command=airflow celery worker
; autostart=true
; autorestart=true
; stderr_logfile=/airflow/app/logs/worker.err.log
; stdout_logfile=/airflow/app/logs/worker.out.log
