# # Source for Kafka Logs
# <source>
#   @type tail
#   path /var/log/kafka/*.log  # Path to Kafka logs directory
#   pos_file /fluentd/log/kafka-log.pos
#   tag kafka.logs
#   <parse>
#     @type none
#   </parse>
# </source>

# Source for Forwarded Logs (Airflow, Docker, etc.)
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# Match and Forward Kafka Logs to Elasticsearch
<match kafka.logs>
  @type elasticsearch
  host es01  # Elasticsearch service name in Docker Compose
  port 9200
  index_name kafka-logs-index
  logstash_format true
  logstash_prefix fluentd-kafka
  flush_interval 5s
</match>

# Match and Forward Airflow Logs to Elasticsearch
<match airflow.logs.**>
  @type elasticsearch
  host es01
  port 9200
  index_name airflow-logs-index
  logstash_format true
  logstash_prefix fluentd-airflow
  flush_interval 5s
</match>

# Match and Forward General Logs (other Docker logs or applications) to Elasticsearch and Console
<match *.**>
  @type copy
  
  # Send logs to Elasticsearch
  <store>
    @type elasticsearch
    host es01
    port 9200
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    tag_key @log_name
    flush_interval 5s
  </store>
  
  # Print logs to stdout for debug purposes
  <store>
    @type stdout
  </store>
</match>
