# Source for Forwarded Logs (Airflow, Docker, etc.)
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<source>
  @type http
  port 9880
  bind 0.0.0.0
  <parse>
    @type json
  </parse>
  body_size_limit 32m
  keepalive_timeout 10s
</source>

<filter airflow.logs.**>
  @type parser
  key_name log
  format json
  reserve_data true
  emit_invalid_record_to_error true
</filter>

# Match and Forward Kafka Logs to Elasticsearch
# <match kafka.logs>
#   @type elasticsearch
#   host es01  # Elasticsearch service name in Docker Compose
#   port 9200
#   index_name kafka-logs-index
#   logstash_format true
#   logstash_prefix fluentd-kafka
#   flush_interval 5s
# </match>

<match airflow.logs.**>
  @type copy
  
  # Send logs to Elasticsearch
  <store>
    @type elasticsearch
    host es01
    port 9200
    index_name airflow-logs-index
    logstash_format true
    logstash_prefix fluentd-airflow
    flush_interval 5s
  </store>
  
  # Send logs to Docker console (stdout) for debugging purposes
  <store>
    @type stdout
  </store>
</match>

# Match and Forward General Logs (other Docker logs or applications) to Elasticsearch and Console
<match *.**>
  @type copy
  
  # Send logs to Elasticsearch
  <store>
    @type elasticsearch
    host es01
    port 9200
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    tag_key @log_name
    flush_interval 5s
  </store>
  
  # Print logs to stdout for debug purposes
  <store>
    @type stdout
  </store>
</match>
