spark.eventLog.enabled           true
spark.eventLog.dir               file:/data/spark-logs
spark.history.fs.logDirectory    file:/data/spark-logs
spark.master spark://spark-master:7077
spark.worker.cleanup.enabled true
spark.worker.cleanup.interval 600
spark.deploy.recoveryMode NONE # Disables the use of rsync/ssh
spark.submit.deployMode          client
spark.network.timeout           600s
spark.rpc.message.maxSize      256
spark.worker.cores 2
spark.worker.memory 2G
